nibrs_property_segment

This setup file is based on original files created using the R package asciiSetupReader(version 2.3.1) on 2020-03-17 11:01:01. This file has been modified to utilize the NIBRS ICPSR variable names based on the documentation available here: https://www.icpsr.umich.edu/web/pages/NACJD/NIBRS/varlist.html#Batch2.


data list
V3001    1-2
V3002       3-4
V3003       5-13
V3004       14-25
V3005       26-33
V3006       34
V3007       35-36
V3008       37-45
V3009       46-53
V3010      54-55
V3011      56-57
V3012      58
V3013      59-67
V3014      68-70
V3015      71-72
V3016      73
V3017      74-82
V3018      83-85
V3019      86-87
V3020      88
V3021      89-97
V3022      98-100
V3023      101-102
.

variable labels
V3001    "segment_level"
V3002    "state"
V3003    "ori"
V3004    "incident_number"
V3005    "incident_date"
V3006    "type_of_property_loss"
V3007    "property_description"
V3008    "value_of_property"
V3009    "date_recovered"
V3010    "number_of_stolen_motor_vehicles"
V3011    "num_of_recovered_motor_vehicles"
V3012    "suspected_drug_type_1"
V3013    "estimated_quantity_1"
V3014    "est_quantity_fractional_1000th_1"
V3015    "type_of_measurement_1"
V3016    "suspected_drug_type_2"
V3017    "estimated_quantity_2"
V3018    "est_quantity_fractional_1000th_2"
V3019    "type_of_measurement_2"
V3020    "suspected_drug_type_3"
V3021    "estimated_quantity_3"
V3022    "est_quantity_fractional_1000th_3"
V3023    "type_of_measurement_3"
.

value labels
V3002               
'50'             "Alaska"
'01'             "Alabama"
'03'             "Arkansas"
'54'             "American Samoa"
'02'             "Arizona"
'04'             "California"
'05'             "Colorado"
'06'             "Connecticut"
'52'             "Canal Zone"
'08'             "District of Columbia"
'07'             "Delaware"
'09'             "Florida"
'10'             "Georgia"
'55'             "Guam"
'51'             "Hawaii"
'14'             "Iowa"
'11'             "Idaho"
'12'             "Illinois"
'13'             "Indiana"
'15'             "Kansas"
'16'             "Kentucky"
'17'             "Louisiana"
'20'             "Massachusetts"
'19'             "Maryland"
'18'             "Maine"
'21'             "Michigan"
'22'             "Minnesota"
'24'             "Missouri"
'23'             "Mississippi"
'25'             "Montana"
'26'             "Nebraska"
'32'             "North Carolina"
'33'             "North Dakota"
'28'             "New Hampshire"
'29'             "New Jersey"
'30'             "New Mexico"
'27'             "Nevada"
'31'             "New York"
'34'             "Ohio"
'35'             "Oklahoma"
'36'             "Oregon"
'37'             "Pennsylvania"
'53'             "Puerto Rico"
'38'             "Rhode Island"
'39'             "South Carolina"
'40'             "South Dakota"
'41'             "Tennessee"
'42'             "Texas"
'43'             "Utah"
'62'             "Virgin Islands"
'45'             "Virginia"
'44'             "Vermont"
'46'             "Washington"
'48'             "Wisconsin"
'47'             "West Virginia"
'49'             "Wyoming"
V3015              
'GM'             "gram"
'KG'             "kilogram"
'OZ'             "ounce"
'LB'             "pound"
'ML'             "milliliter"
'LT'             "liter"
'FO'             "fluid ounce"
'GL'             "gallon"
'DU'             "dosage unit/items (pills, etc.)"
'NP'             "number of plants"
'XX'             "not reported"
V3012              
'A'              "crack cocaine"
'B'              "cocaine (all forms except crack)"
'C'              "hashish"
'D'              "heroin"
'E'              "marijuana"
'F'              "morphine"
'G'              "opium"
'H'              "other narcotics: codeine, demerol, dihydromorphinone or dilaudid, hydrocodone or percodan, methadone, etc."
'I'              "LSD"
'P'              "PCP"
'K'              "other hallucinogrens: BMDA (white acid), DMT, MDA, MDMA, mescaline or peyote, psilocybin, STP, etc."
'L'              "amphetamines/methamphetamines"
'M'              "other stimulants: adipex, fastine and ionamin (derivatives of phentermine), benzedrine, didrex, methylphenidate or ritalin, phenmetrazine or preludin, tenuate, etc."
'N'              "barbiturates"
'O'              "other depressants: glutethimide or doriden, methaqualone or quaalude, pentazocine or talwin, etc."
'P'              "other drugs: antidepressants (elavil, triavil, tofranil, etc.), aromatic hydrocarbons, propoxyphene or darvon, tranquilizers (chlordiazepoxide or librium, diazepam or valium, etc.), etc."
'U'              "unknown type drug"
'X'              "over 3 drug types"
'J'              "PCP"
V3019              
'GM'             "gram"
'KG'             "kilogram"
'OZ'             "ounce"
'LB'             "pound"
'ML'             "milliliter"
'LT'             "liter"
'FO'             "fluid ounce"
'GL'             "gallon"
'DU'             "dosage unit/items (pills, etc.)"
'NP'             "number of plants"
'XX'             "not reported"
V3016              
'A'              "crack cocaine"
'B'              "cocaine (all forms except crack)"
'C'              "hashish"
'D'              "heroin"
'E'              "marijuana"
'F'              "morphine"
'G'              "opium"
'H'              "other narcotics: codeine, demerol, dihydromorphinone or dilaudid, hydrocodone or percodan, methadone, etc."
'I'              "LSD"
'P'              "PCP"
'K'              "other hallucinogrens: BMDA (white acid), DMT, MDA, MDMA, mescaline or peyote, psilocybin, STP, etc."
'L'              "amphetamines/methamphetamines"
'M'              "other stimulants: adipex, fastine and ionamin (derivatives of phentermine), benzedrine, didrex, methylphenidate or ritalin, phenmetrazine or preludin, tenuate, etc."
'N'              "barbiturates"
'O'              "other depressants: glutethimide or doriden, methaqualone or quaalude, pentazocine or talwin, etc."
'P'              "other drugs: antidepressants (elavil, triavil, tofranil, etc.), aromatic hydrocarbons, propoxyphene or darvon, tranquilizers (chlordiazepoxide or librium, diazepam or valium, etc.), etc."
'U'              "unknown type drug"
'X'              "over 3 drug types"
'J'              "PCP"
V3023              
'GM'             "gram"
'KG'             "kilogram"
'OZ'             "ounce"
'LB'             "pound"
'ML'             "milliliter"
'LT'             "liter"
'FO'             "fluid ounce"
'GL'             "gallon"
'DU'             "dosage unit/items (pills, etc.)"
'NP'             "number of plants"
'XX'             "not reported"
V3020              
'A'              "crack cocaine"
'B'              "cocaine (all forms except crack)"
'C'              "hashish"
'D'              "heroin"
'E'              "marijuana"
'F'              "morphine"
'G'              "opium"
'H'              "other narcotics: codeine, demerol, dihydromorphinone or dilaudid, hydrocodone or percodan, methadone, etc."
'I'              "LSD"
'P'              "PCP"
'K'              "other hallucinogrens: BMDA (white acid), DMT, MDA, MDMA, mescaline or peyote, psilocybin, STP, etc."
'L'              "amphetamines/methamphetamines"
'M'              "other stimulants: adipex, fastine and ionamin (derivatives of phentermine), benzedrine, didrex, methylphenidate or ritalin, phenmetrazine or preludin, tenuate, etc."
'N'              "barbiturates"
'O'              "other depressants: glutethimide or doriden, methaqualone or quaalude, pentazocine or talwin, etc."
'P'              "other drugs: antidepressants (elavil, triavil, tofranil, etc.), aromatic hydrocarbons, propoxyphene or darvon, tranquilizers (chlordiazepoxide or librium, diazepam or valium, etc.), etc."
'U'              "unknown type drug"
'X'              "over 3 drug types"
'J'              "PCP"
V3006               
'1'              "none"
'2'              "burned"
'3'              "counterfeited/forged"
'4'              "destroyed/damaged/vandalized"
'5'              "recovered"
'6'              "seized"
'7'              "stolen/etc. (includes bribed, defrauded, embezzled, extorted, ransomed, robbed, etc.)"
'8'              "unknown"
V3007               
'01'             "aircraft"
'02'             "alcohol"
'03'             "automobiles"
'04'             "bicycles"
'05'             "buses"
'06'             "clothes/furs"
'07'             "computer hardware/software"
'08'             "consumable goods"
'09'             "credit/debit cards"
'10'             "drugs/narcotics"
'11'             "drug/narcotic equipment"
'12'             "farm equipment"
'13'             "firearms"
'14'             "gambling equipment"
'15'             "heavy construction/industrial equipment"
'16'             "household goods"
'17'             "jewelry/precious metals"
'18'             "livestock"
'19'             "merchandise"
'20'             "money"
'21'             "negotiable instruments"
'22'             "nonnegotiable instruments"
'23'             "office-type equipment"
'24'             "other motor vehicles"
'25'             "purses/handbags/wallets"
'26'             "radios/TVs/VCRs"
'27'             "recordings - audio/visual"
'28'             "recreational vehicles"
'29'             "structures - single occupancy dwellings"
'30'             "structures - other dwellings"
'31'             "structures - commercial/business"
'32'             "structures - industrial manufacturing"
'33'             "structures - public/community"
'34'             "structures - storage"
'35'             "structures - other"
'36'             "tools - power/hand"
'37'             "trucks"
'38'             "vehicle parts/accessories"
'39'             "watercraft"
'77'             "other"
'88'             "pending inventory (of property)"
'99'             "special category"
'41'             "aircraft parts/accessories"
'42'             "artistic supplies/accessories"
'43'             "building materials"
'44'             "camping/hunting/fishing equipment/supplies"
'45'             "chemicals"
'46'             "collections/collectibles"
'47'             "crops"
'48'             "documents - personal or business"
'49'             "explosives"
'59'             "firearm accessories"
'64'             "fuel"
'65'             "identity documents"
'66'             "identity - intangible"
'67'             "law enforcement equipment"
'68'             "lawn/yard/garden equipment"
'69'             "logging equipment"
'70'             "medical/medical lab equipment"
'71'             "metals, non-precious"
'72'             "musical instruments"
'73'             "pets"
'74'             "photographic/optical equipment"
'75'             "portible electronic communications"
'76'             "recreational/sports equipment"
'78'             "trailers"
'79'             "watercraft equipment/parts/accessories"
'80'             "weapons - other"
V3008               
'000000001'      "unknown"
.



execute
